### ISSUE TITLE
Hello!

### ISSUE THREAD

**Issue by avindra** [ellier7/PHQ-9_screener#4]
Hi Ellie 👋 

I'm one of the app engineers at Quartet and I've just done a review of your exercise. I like the frontend design you put together, and I think it's super cool that it's deployed to heroku! Here are some things I would be curious to see your response to.

* First, instead of using `createClass`, could you use stateless functional components instead, or ES6 classes if necessary?
* Secondly, I found a minor bug 🐛  where multiple responses are highlighted if you try to select more than one:

# 1
![screen shot 2016-12-16 at 12 53 31 pm](https://cloud.githubusercontent.com/assets/126848/21272898/128f24cc-c38f-11e6-91c7-1d916071b03a.png)

# 2
![screen shot 2016-12-16 at 12 53 35 pm](https://cloud.githubusercontent.com/assets/126848/21272906/182a6496-c38f-11e6-9aed-26a57f1381f7.png)

# 3
![screen shot 2016-12-16 at 12 53 39 pm](https://cloud.githubusercontent.com/assets/126848/21272919/1d33826a-c38f-11e6-877f-86c661090d20.png)

I would like to see if you can identify the issue here, and push out a fix for it.

Additionally, it would be nice to have some more granular usage of the `connect` function-- currently it is just on the top level component. Could you possibly identify patterns where you could expose the state to only components that need it?

Please feel free to reach out to me with any questions or concerns you have, looking forward to hearing your response!

**Comment by ellier7** [comment]
Hi Avindra,
I have made the changes you mentioned above and pushed to my master branch. Please let me know if you have any questions.

Thanks!
